name: cafe_app_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.3
  flutter_icons:
  get: 4.3.8
  # camerawesome: 0.3.0
  # image_picker: 0.8.4
  # photo_view: 0.13.0
  flutter_spinkit: 5.1.0
  filling_slider: 0.0.3
  # url_launcher: 6.0.18
  flutter_svg: 1.0.3
  # bottom_sheet_bar: 2.1.1
  flutter_screenutil: 5.1.1
  bubble_bottom_bar: 2.0.0
  google_fonts: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
